/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse and search the catalogue */
        get: operations["searchGames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{sku}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One game's page */
        get: operations["getGame"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/genres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every genre, with how many games it has */
        get: operations["listGenres"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everything the home page shows, in one request */
        get: operations["getHome"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who is signed in */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/outbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The unpublished tail of the outbox */
        get: operations["opsOutbox"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reservations, newest first */
        get: operations["opsReservations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock levels, in SKU order */
        get: operations["opsStock"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/stock/{sku}/adjust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add or remove stock directly */
        post: operations["opsAdjust"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your orders, newest first */
        get: operations["listOrders"];
        put?: never;
        /** Place an order, holding its stock */
        post: operations["placeOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One of your orders */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel an unpaid order, giving its stock back */
        post: operations["cancelOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pay for an order (demonstration — no money moves) */
        post: operations["payOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Facet: {
            /** Format: int64 */
            count: number;
            value: string;
        };
        Facets: {
            genres: components["schemas"]["Facet"][];
            tags: components["schemas"]["Facet"][];
        };
        GameCard: {
            /** Format: date-time */
            availabilityAsOf: string | null;
            /** Format: int64 */
            available: number;
            blurb: string;
            cover: string;
            currency: string;
            /** Format: int32 */
            discountPercent: number;
            genre: string;
            /** Format: int64 */
            listPriceCents: number;
            /** Format: int64 */
            priceCents: number;
            /** Format: date */
            releasedOn: string;
            sku: string;
            studio: string;
            tags: string[];
            title: string;
        };
        GameDetail: {
            description: string;
            features: string[];
            game: components["schemas"]["GameCard"];
            related: components["schemas"]["GameCard"][];
        };
        GamePage: {
            facets: components["schemas"]["Facets"];
            items: components["schemas"]["GameCard"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            total: number;
        };
        Home: {
            bestSellers: components["schemas"]["GameCard"][];
            featured: components["schemas"]["GameCard"][];
            genres: components["schemas"]["Facet"][];
            newReleases: components["schemas"]["GameCard"][];
            onSale: components["schemas"]["GameCard"][];
        };
        LineRequest: {
            /** Format: int32 */
            quantity: number;
            sku: string;
        };
        Logout: {
            redirect: string;
        };
        Me: {
            admin: boolean;
            authenticated: boolean;
            email: string | null;
            name: string | null;
        };
        OpsAdjust: {
            /** Format: int64 */
            delta: number;
        };
        OpsLine: {
            /** Format: int64 */
            quantity: number;
            sku: string;
        };
        OpsOutboxEntry: {
            dedupeKey: string;
            payload: string;
            /** Format: date-time */
            recordedAt: string;
            /** Format: int64 */
            sequence: number;
        };
        OpsOutboxPage: {
            /** Format: int64 */
            backlog: number;
            items: components["schemas"]["OpsOutboxEntry"][];
        };
        OpsReservation: {
            /** Format: date-time */
            createdAt: string;
            /** @enum {string} */
            effectiveState: "HELD" | "COMMITTED" | "RELEASED" | "EXPIRED";
            /** Format: date-time */
            expiresAt: string;
            id: string;
            lines: components["schemas"]["OpsLine"][];
            /** @enum {string} */
            state: "HELD" | "COMMITTED" | "RELEASED" | "EXPIRED";
        };
        OpsReservationPage: {
            items: components["schemas"]["OpsReservation"][];
        };
        OpsStock: {
            /** Format: int64 */
            available: number;
            /** Format: int64 */
            onHand: number;
            /** Format: int64 */
            reserved: number;
            sku: string;
            title: string | null;
        };
        OpsStockPage: {
            items: components["schemas"]["OpsStock"][];
            nextAfter: string | null;
        };
        Order: {
            /** Format: date-time */
            closedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            currency: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: uuid */
            id: string;
            lines: components["schemas"]["OrderLine"][];
            /** @enum {string} */
            status: "PENDING" | "PAID" | "CANCELLED" | "EXPIRED";
            /** Format: int64 */
            totalCents: number;
        };
        OrderLine: {
            cover: string | null;
            /** Format: int32 */
            quantity: number;
            sku: string;
            title: string;
            /** Format: int64 */
            unitPriceCents: number;
        };
        OrderPage: {
            items: components["schemas"]["Order"][];
        };
        PlaceOrder: {
            lines: components["schemas"]["LineRequest"][];
        };
        /** @description An RFC 9457 problem, with a machine-readable code. */
        Problem: {
            /** @description NOT_FOUND, INSUFFICIENT_STOCK, UNKNOWN_SKU, ORDER_EXPIRED, ORDER_CANCELLED, ORDER_PAID, IDEMPOTENCY_KEY_REUSED, LEDGER_UNAVAILABLE, BAD_REQUEST, INVALID_BODY, MISSING_HEADER, UNAUTHORIZED, FORBIDDEN, CSRF, INTERNAL_ERROR; otherwise the name of the HTTP status */
            code: string;
            detail: string;
            errors?: components["schemas"]["ProblemFieldError"][];
            instance?: string;
            shortfalls?: components["schemas"]["ProblemShortfall"][];
            /** Format: int32 */
            status: number;
            title: string;
            type?: string;
        };
        ProblemFieldError: {
            field: string;
            message: string;
        };
        ProblemShortfall: {
            /** Format: int64 */
            available: number;
            /** Format: int64 */
            requested: number;
            sku: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchGames: {
        parameters: {
            query?: {
                q?: string;
                genre?: string;
                tag?: string;
                maxPriceCents?: number;
                onSale?: boolean;
                sort?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GamePage"];
                };
            };
            /** @description Refused or failed; `code` says why. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetail"];
                };
            };
            /** @description Refused or failed; `code` says why. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listGenres: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Facet"][];
                };
            };
            /** @description Refused or failed; `code` says why. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getHome: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Home"];
                };
            };
            /** @description Refused or failed; `code` says why. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Logout"];
                };
            };
            /** @description Refused or failed; `code` says why. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Refused or failed; `code` says why. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    opsOutbox: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsOutboxPage"];
                };
            };
            /** @description Refused or failed; `code` says why. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    opsReservations: {
        parameters: {
            query?: {
                state?: "HELD" | "COMMITTED" | "RELEASED" | "EXPIRED";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsReservationPage"];
                };
            };
            /** @description Refused or failed; `code` says why. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    opsStock: {
        parameters: {
            query?: {
                limit?: number;
                after?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsStockPage"];
                };
            };
            /** @description Refused or failed; `code` says why. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    opsAdjust: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                sku: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpsAdjust"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsStock"];
                };
            };
            /** @description Refused or failed; `code` says why. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderPage"];
                };
            };
            /** @description Refused or failed; `code` says why. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    placeOrder: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceOrder"];
            };
        };
        responses: {
            /** @description Placed — or, for a key already used, the order it placed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description Refused or failed; `code` says why. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description Refused or failed; `code` says why. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    cancelOrder: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description Refused or failed; `code` says why. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    payOrder: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description Refused or failed; `code` says why. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
