/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/outbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The unpublished tail of the outbox */
        get: operations["listOutbox"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reservations, newest first */
        get: operations["listReservations"];
        put?: never;
        /** Take a hold on stock */
        post: operations["reserve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Look a hold up */
        get: operations["getReservation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservations/{id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Turn a hold into a sale */
        post: operations["commitReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservations/{id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Give a hold back */
        post: operations["releaseReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stock levels */
        get: operations["listStock"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stock/{sku}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a stock level */
        get: operations["getStock"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stock/{sku}/adjust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change on-hand stock directly */
        post: operations["adjustStock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdjustRequest: {
            /** Format: int64 */
            delta: number;
        };
        Committed: {
            /** Format: date-time */
            committedAt: string;
            id: string;
        };
        Line: {
            /** Format: int64 */
            quantity: number;
            sku: string;
        };
        OutboxEntry: {
            dedupeKey: string;
            payload: string;
            /** Format: date-time */
            recordedAt: string;
            /** Format: int64 */
            sequence: number;
        };
        OutboxPage: {
            /** Format: int64 */
            backlog: number;
            items: components["schemas"]["OutboxEntry"][];
        };
        /** @description An RFC 9457 problem detail. */
        Problem: {
            /**
             * @example INSUFFICIENT_STOCK
             * @enum {string}
             */
            code?: "INSUFFICIENT_STOCK" | "UNKNOWN_SKU" | "RESERVATION_NOT_FOUND" | "RESERVATION_EXPIRED" | "ALREADY_COMMITTED" | "ALREADY_RELEASED" | "RESERVATION_ID_IN_USE" | "IDEMPOTENCY_KEY_REUSED" | "CONTENTION" | "UNAUTHORIZED" | "FORBIDDEN";
            /** @example widget: asked for 5, 2 available */
            detail: string;
            instance?: string;
            /** @example 0f9c1a7e-1f3a-4a2b-9a1e-2c4d6e8f0a11 */
            requestId?: string;
            shortfalls?: components["schemas"]["Shortfall"][];
            /**
             * Format: int32
             * @example 409
             */
            status: number;
            /** @example Not enough stock */
            title: string;
            /** @example about:blank */
            type?: string;
        };
        Released: {
            id: string;
            /** Format: date-time */
            releasedAt: string;
        };
        Reservation: {
            /** Format: date-time */
            createdAt: string;
            /** @enum {string} */
            effectiveState: "HELD" | "COMMITTED" | "RELEASED" | "EXPIRED";
            /** Format: date-time */
            expiresAt: string;
            id: string;
            lines: components["schemas"]["Line"][];
            /** @enum {string} */
            state: "HELD" | "COMMITTED" | "RELEASED" | "EXPIRED";
        };
        ReservationPage: {
            items: components["schemas"]["Reservation"][];
        };
        ReserveRequest: {
            lines: components["schemas"]["Line"][];
            /**
             * Format: int64
             * @description How long the hold lasts. Defaults to till.default-ttl.
             * @example 900
             */
            ttlSeconds?: number;
        };
        Reserved: {
            /** Format: date-time */
            expiresAt: string;
            id: string;
            lines: components["schemas"]["Line"][];
        };
        Shortfall: {
            /** Format: int64 */
            available: number;
            /** Format: int64 */
            requested: number;
            sku: string;
        };
        Stock: {
            /** Format: int64 */
            available: number;
            /** Format: int64 */
            onHand: number;
            /** Format: int64 */
            reserved: number;
            sku: string;
        };
        StockPage: {
            items: components["schemas"]["Stock"][];
            /** @description Absent on the last page. */
            nextAfter?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listOutbox: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the backlog and its oldest entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OutboxPage"];
                };
            };
            /** @description the request could not be read, or a value in it was not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description no bearer token, or one this service does not know */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description this needs the admin token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listReservations: {
        parameters: {
            query?: {
                state?: "HELD" | "COMMITTED" | "RELEASED" | "EXPIRED";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReservationPage"];
                };
            };
            /** @description the request could not be read, or a value in it was not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description no bearer token, or one this service does not know */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    reserve: {
        parameters: {
            query?: never;
            header: {
                /** @description Retrying with this key returns the first answer and changes nothing */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReserveRequest"];
            };
        };
        responses: {
            /** @description the hold was taken, or already existed under this key */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Reserved"];
                };
            };
            /** @description the request could not be read, or a value in it was not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description no bearer token, or one this service does not know */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description a SKU has never been stocked */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description not enough available stock; the body lists every shortfall */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description this key was used for a different request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description too much contention; retry */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getReservation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the reservation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Reservation"];
                };
            };
            /** @description the request could not be read, or a value in it was not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description no bearer token, or one this service does not know */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description no such reservation */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    commitReservation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description on-hand and reserved both went down */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Committed"];
                };
            };
            /** @description the request could not be read, or a value in it was not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description no bearer token, or one this service does not know */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description no such reservation */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description already committed, or already released */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description the hold ran out of time */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    releaseReservation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the hold is gone, whether it went now or earlier */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Released"];
                };
            };
            /** @description the request could not be read, or a value in it was not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description no bearer token, or one this service does not know */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description no such reservation */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description it was committed and cannot be released */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listStock: {
        parameters: {
            query?: {
                limit?: number;
                after?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StockPage"];
                };
            };
            /** @description the request could not be read, or a value in it was not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description no bearer token, or one this service does not know */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getStock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the level */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Stock"];
                };
            };
            /** @description the request could not be read, or a value in it was not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description no bearer token, or one this service does not know */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description this SKU has never been stocked */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    adjustStock: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                sku: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdjustRequest"];
            };
        };
        responses: {
            /** @description the new level */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Stock"];
                };
            };
            /** @description the request could not be read, or a value in it was not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description no bearer token, or one this service does not know */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description this needs the admin token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description removing stock from a SKU that has no row */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description this would take on-hand below what is reserved */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
